export const MOVIES = [
  {
    id: 1,
    title: "센과 치히로의 행방불명",
    imageUrl: "/images/movie_thumbnail1.webp",
  },
  { id: 2, title: "모노노케 히메", imageUrl: "/images/movie_thumbnail2.webp" },
  {
    id: 3,
    title: "하울의 움직이는 성",
    imageUrl: "/images/movie_thumbnail3.webp",
  },
  { id: 4, title: "벼랑 위의 포뇨", imageUrl: "/images/movie_thumbnail4.webp" },
  {
    id: 5,
    title: "센토령 인텔리전스",
    imageUrl: "/images/movie_thumbnail5.webp",
  },
  { id: 6, title: "식스 센스", imageUrl: "/images/movie_thumbnail6.webp" },
  { id: 7, title: "세나 F1의 신화", imageUrl: "/images/movie_thumbnail7.webp" },
  { id: 8, title: "컬렉션", imageUrl: "/images/movie_thumbnail8.webp" },
  {
    id: 9,
    title: "하울의 움직이는 성 2",
    imageUrl: "/images/movie_thumbnail9.webp",
  },
  {
    id: 10,
    title: "이웃집 토토로",
    imageUrl: "/images/movie_thumbnail10.webp",
  },
  {
    id: 11,
    title: "마루 밑 아리에티",
    imageUrl: "/images/movie_thumbnail1.webp",
  },
  { id: 12, title: "고양이의 보은", imageUrl: "/images/movie_thumbnail2.webp" },
  {
    id: 13,
    title: "추억의 마블 일",
    imageUrl: "/images/movie_thumbnail3.webp",
  },
  {
    id: 14,
    title: "바람 계곡의 나우시카",
    imageUrl: "/images/movie_thumbnail4.webp",
  },
  { id: 15, title: "붉은 돼지", imageUrl: "/images/movie_thumbnail5.webp" },
  { id: 16, title: "게드 전기", imageUrl: "/images/movie_thumbnail6.webp" },
  {
    id: 17,
    title: "센과 치히로 특별판",
    imageUrl: "/images/movie_thumbnail7.webp",
  },
  {
    id: 18,
    title: "추억은 방울방울",
    imageUrl: "/images/movie_thumbnail8.webp",
  },
  { id: 19, title: "반딧불이의 묘", imageUrl: "/images/movie_thumbnail9.webp" },
  {
    id: 20,
    title: "센과 함께하는 여행",
    imageUrl: "/images/movie_thumbnail10.webp",
  },
  { id: 21, title: "원더풀 라이프", imageUrl: "/images/movie_thumbnail1.webp" },
  {
    id: 22,
    title: "센과 치히로 리마스터",
    imageUrl: "/images/movie_thumbnail2.webp",
  },
  { id: 23, title: "공각기동대", imageUrl: "/images/movie_thumbnail3.webp" },
  { id: 24, title: "아키라", imageUrl: "/images/movie_thumbnail4.webp" },
  {
    id: 25,
    title: "센과 마법의 왕국",
    imageUrl: "/images/movie_thumbnail5.webp",
  },
  {
    id: 26,
    title: "천공의 성 라퓨타",
    imageUrl: "/images/movie_thumbnail6.webp",
  },
  { id: 27, title: "귀를 기울이면", imageUrl: "/images/movie_thumbnail7.webp" },
  {
    id: 28,
    title: "센과 함께 떠나는 모험",
    imageUrl: "/images/movie_thumbnail8.webp",
  },
  {
    id: 29,
    title: "코쿠리코 언덕에서",
    imageUrl: "/images/movie_thumbnail9.webp",
  },
  {
    id: 30,
    title: "센의 비밀 정원",
    imageUrl: "/images/movie_thumbnail10.webp",
  },
  {
    id: 31,
    title: "센과 마법사의 돌",
    imageUrl: "/images/movie_thumbnail1.webp",
  },
  { id: 32, title: "추억 속의 센", imageUrl: "/images/movie_thumbnail2.webp" },
  {
    id: 33,
    title: "센과 용의 전설",
    imageUrl: "/images/movie_thumbnail3.webp",
  },
  { id: 34, title: "퍼펙트 블루", imageUrl: "/images/movie_thumbnail4.webp" },
  { id: 35, title: "파프리카", imageUrl: "/images/movie_thumbnail5.webp" },
  {
    id: 36,
    title: "센과 숲의 정령",
    imageUrl: "/images/movie_thumbnail6.webp",
  },
  {
    id: 37,
    title: "시간을 달리는 소녀",
    imageUrl: "/images/movie_thumbnail7.webp",
  },
  { id: 38, title: "늑대아이", imageUrl: "/images/movie_thumbnail8.webp" },
  {
    id: 39,
    title: "센과 바다의 노래",
    imageUrl: "/images/movie_thumbnail9.webp",
  },
  {
    id: 40,
    title: "센과 별의 목소리",
    imageUrl: "/images/movie_thumbnail10.webp",
  },
  { id: 41, title: "카우보이 비밥", imageUrl: "/images/movie_thumbnail1.webp" },
  {
    id: 42,
    title: "센과 꿈의 세계",
    imageUrl: "/images/movie_thumbnail2.webp",
  },
  {
    id: 43,
    title: "센과 불의 여신",
    imageUrl: "/images/movie_thumbnail3.webp",
  },
  {
    id: 44,
    title: "바케모노의 아이",
    imageUrl: "/images/movie_thumbnail4.webp",
  },
  {
    id: 45,
    title: "센과 미래의 미라이",
    imageUrl: "/images/movie_thumbnail5.webp",
  },
  { id: 46, title: "너의 이름은", imageUrl: "/images/movie_thumbnail6.webp" },
  { id: 47, title: "날씨의 아이", imageUrl: "/images/movie_thumbnail7.webp" },
  {
    id: 48,
    title: "센과 빛나는 계절",
    imageUrl: "/images/movie_thumbnail8.webp",
  },
  {
    id: 49,
    title: "센과 황혼의 노래",
    imageUrl: "/images/movie_thumbnail9.webp",
  },
  {
    id: 50,
    title: "센과 새벽의 전설",
    imageUrl: "/images/movie_thumbnail10.webp",
  },
];

export const CAROUSELS = [
  {
    id: 1,
    title: "꼭 챙겨보세요! 회원님을 위한 콘텐츠",
    itemsPerView: 6,
    stepSize: 3,
    items: [
      { id: 1, imageUrl: "/images/movie_thumbnail1.webp" },
      { id: 2, imageUrl: "/images/movie_thumbnail2.webp" },
      { id: 3, imageUrl: "/images/movie_thumbnail3.webp" },
      { id: 4, imageUrl: "/images/movie_thumbnail4.webp" },
      { id: 5, imageUrl: "/images/movie_thumbnail5.webp" },
      { id: 6, imageUrl: "/images/movie_thumbnail6.webp" },
      { id: 7, imageUrl: "/images/movie_thumbnail7.webp" },
      { id: 8, imageUrl: "/images/movie_thumbnail8.webp" },
      { id: 9, imageUrl: "/images/movie_thumbnail9.webp" },
      { id: 10, imageUrl: "/images/movie_thumbnail10.webp" },
    ],
  },
  {
    id: 2,
    title: "상상의 나래를 펼친 영화",
    itemsPerView: 6,
    stepSize: 6,
    items: [
      { id: 4, imageUrl: "/images/movie_thumbnail4.webp" },
      { id: 5, imageUrl: "/images/movie_thumbnail5.webp" },
      { id: 6, imageUrl: "/images/movie_thumbnail6.webp" },
      { id: 7, imageUrl: "/images/movie_thumbnail7.webp" },
      { id: 8, imageUrl: "/images/movie_thumbnail8.webp" },
      { id: 9, imageUrl: "/images/movie_thumbnail9.webp" },
      { id: 10, imageUrl: "/images/movie_thumbnail10.webp" },
    ],
  },
  {
    id: 3,
    title: "어워드 수상 영화",
    itemsPerView: 6,
    stepSize: 5,
    items: [
      { id: 6, imageUrl: "/images/movie_thumbnail6.webp" },
      { id: 7, imageUrl: "/images/movie_thumbnail7.webp" },
      { id: 8, imageUrl: "/images/movie_thumbnail8.webp" },
      { id: 9, imageUrl: "/images/movie_thumbnail9.webp" },
      { id: 10, imageUrl: "/images/movie_thumbnail10.webp" },
      { id: 1, imageUrl: "/images/movie_thumbnail1.webp" },
      { id: 2, imageUrl: "/images/movie_thumbnail2.webp" },
      { id: 3, imageUrl: "/images/movie_thumbnail3.webp" },
      { id: 4, imageUrl: "/images/movie_thumbnail4.webp" },
      { id: 5, imageUrl: "/images/movie_thumbnail5.webp" },
    ],
  },
];
