export const carouselData = {
  content1: {
    title: "꼭 챙겨보세요! 회원님을 위한 콘텐츠",
    itemsPerView: 6,
    stepSize: 3,
    items: [
      "/src/assets/images/movie_thumbnail1.webp",
      "/src/assets/images/movie_thumbnail2.webp",
      "/src/assets/images/movie_thumbnail3.webp",
      "/src/assets/images/movie_thumbnail4.webp",
      "/src/assets/images/movie_thumbnail5.webp",
      "/src/assets/images/movie_thumbnail6.webp",
      "/src/assets/images/movie_thumbnail7.webp",
      "/src/assets/images/movie_thumbnail8.webp",
      "/src/assets/images/movie_thumbnail9.webp",
      "/src/assets/images/movie_thumbnail10.webp",
    ],
  },
  content2: {
    title: "상상의 나래를 펼친 영화",
    itemsPerView: 6,
    stepSize: 6,
    items: [
      "/src/assets/images/movie_thumbnail4.webp",
      "/src/assets/images/movie_thumbnail5.webp",
      "/src/assets/images/movie_thumbnail6.webp",
      "/src/assets/images/movie_thumbnail7.webp",
      "/src/assets/images/movie_thumbnail8.webp",
      "/src/assets/images/movie_thumbnail9.webp",
      "/src/assets/images/movie_thumbnail10.webp",
    ],
  },
  content3: {
    title: "어워드 수상 영화",
    itemsPerView: 6,
    stepSize: 5,
    items: [
      "/src/assets/images/movie_thumbnail6.webp",
      "/src/assets/images/movie_thumbnail7.webp",
      "/src/assets/images/movie_thumbnail8.webp",
      "/src/assets/images/movie_thumbnail9.webp",
      "/src/assets/images/movie_thumbnail10.webp",
      "/src/assets/images/movie_thumbnail1.webp",
      "/src/assets/images/movie_thumbnail2.webp",
      "/src/assets/images/movie_thumbnail3.webp",
      "/src/assets/images/movie_thumbnail4.webp",
      "/src/assets/images/movie_thumbnail5.webp",
    ],
  },
};
